function atualizeSingleNeuron3D(varargin, Vmin, Vmax)
%    plot generated by plotStaticMNMorphology3
    
    if nargin == 3
        VArray = varargin{1};
        Vmin = varargin{2};
        Vmax = varargin{3};
    end
    
    cmapHot = colormap('hot');
    
    global NAS;
    
    isColoredTrees = NAS.guiData.single.isShowColoredTrees;
    isShowSectionOnly = NAS.guiData.single.isShowSectionOnly;
    isShowSection = NAS.guiData.single.isShowSection;
    baseColor = NAS.guiData.single.baseColor;
    sectionColor = NAS.guiData.single.sectionColor;
    isShowSingleTree = NAS.guiData.single.isShowSingleTree;
    isAnimation = NAS.guiData.single.isAnimation;
    
    visualizationBoxLength = 0;
    numOfSegments = NAS.data.properties.('custom').numOfSegments;
    surface_handle = NAS.guiData.single.surface_handle;
    type = NAS.data.properties.('custom').('data').('local').('type');
    parent = NAS.data.properties.('custom').('data').('local').('parent');
    specifiedOrder = 0;
    zeroOrderSegments = NAS.data.properties.('custom').('data').('zeroOrderSegments');
    stemParent = NAS.data.properties.('custom').('data').('local').('stemParent');
    cmap = NAS.guiData.single.cmap_general;
    
    sectionIndexes =  getCompartmentIndexesBySection5(NAS.data.properties.('custom'), NAS.guiData.single.d_min,...
                                                        NAS.guiData.single.d_max, specifiedOrder, NAS.guiData.single.metric);

    for i = 1:numOfSegments
        
        if type(i)==1 && parent(i)==1 %% Skip false compartments
            continue;
        end
        
        if isShowSectionOnly && ~sectionIndexes(i)
            continue;
        else
            set(surface_handle(i),'FaceColor',baseColor,'EdgeColor', baseColor,'FaceAlpha',1.0);
        end
        
        set(surface_handle(i),'FaceColor',baseColor,'EdgeColor', baseColor,'FaceAlpha',0.7);
        
        if isAnimation
            color = getColor(cmapHot, VArray(i), Vmin, Vmax);
            set(surface_handle(i),'FaceColor',color,'EdgeColor', color,'FaceAlpha',0.8,'EdgeAlpha',0.8);
        end
            
            
        if isColoredTrees
            
            if type(i)==1
                segmentColor=[0,0,0];
            else
                if nnz(zeroOrderSegments == stemParent(i))
                    segmentColor = cmap(zeroOrderSegments == stemParent(i),:);
                else
                    segmentColor = [1 0 0]; % in case the tree was excluded
                end
            end
            set(surface_handle(i),'FaceColor',segmentColor,'EdgeColor', segmentColor,'FaceAlpha',0.8,'EdgeAlpha',0.8);
        end
        
        if isShowSingleTree
            showOnlyTree = str2num(NAS.guiData.single.showOnlyTree);
            if zeroOrderSegments(showOnlyTree) == stemParent(i)
                set(surface_handle(i),'FaceColor',baseColor,'EdgeColor', baseColor,'FaceAlpha',0.8,'EdgeAlpha',0.8);
            else
                set(surface_handle(i),'FaceColor',baseColor,'EdgeColor', baseColor,'FaceAlpha',0.005,'EdgeAlpha',0.005);
            end
        end
        
        if isShowSection
            if(sectionIndexes(i))
                set(surface_handle(i),'FaceColor',sectionColor,'EdgeColor', sectionColor,'FaceAlpha',0.2);
            end
        end
    end

end

